- name: Build frontend Docker image    #creating image
  docker_image:
    name: "{{ frontend_image }}"
    source: build                       # build image
    build:
      path: "{{ app_path }}/client"

- name: Run frontend container           #run image
  docker_container:
    name: frontend
    image: "{{ frontend_image }}"
    state: started
    ports:
      - "81:80"
    restart_policy: always
